name: Semantic Release

on:
    workflow_call:
    workflow_dispatch:
#     push:
#        branches: [main]
    pull_request:
        branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: pat
        run: |
          echo ${{ secrets.PAT }}
          
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
