name: Semantic Release

on:
    push:
       branches: [main]
    pull_request:
       branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branches: |
            ['main']
          extra_plugins: |
            @semantic-release/commit-analyzer@^6.3.3
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/git
            @semantic-release/changelog
            conventional-changelog-conventionalcommits
            conventional-changelog-eslint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
